[package]
name = "aptest"
version = "0.0.0"
authors = ["Ian Macalinao <ian@aptos.is>"]
license = "Apache-2.0"

[addresses]
std = "0x1"
# Derived from core
aptest = "0xf876de28a7ba37043985456abbc03776c53fc5e6a4ffd88a99e097398ab89c49"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "a026097e1873d6ce2a264c4e162e910bbf5788f3"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "a026097e1873d6ce2a264c4e162e910bbf5788f3"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "a026097e1873d6ce2a264c4e162e910bbf5788f3"
