[package]
name = "aptest"
version = "0.0.0"
authors = ["Ian Macalinao <ian@aptos.is>"]
license = "Apache-2.0"

[readme]
title = "aptest: Aptos Test Utilities"

[addresses]
std = "0x1"
# should never be used in production, so we hardcode this address
aptest = "0xfaceb00c"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"

[dependencies.MoveNursery]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib/nursery"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"
